### ISSUE TITLE
[Error] An error occurred when run main.py

### ISSUE THREAD

**Issue by CaptainEven** [OsamaMazhar/Random-Shadows-Highlights#2]
from efficientnet_pytorch import EfficientNet
ModuleNotFoundError: No module named 'efficientnet_pytorch'

**Comment by OsamaMazhar** [comment]
As suggested in the "Steps", you need to install it from here:
https://github.com/lukemelas/EfficientNet-PyTorch

**Comment by CaptainEven** [comment]
@OsamaMazhar Thanks for quick reply!
